/**
 * Demo content for KantoList — realistic Philippine province classifieds.
 *
 * Kept as plain data, separate from any driver, so the same dataset can be
 * written through Prisma (scripts/seed-demo.ts) or turned into SQL when a
 * direct Postgres connection is not available.
 *
 * Everything here is invented. Names, numbers and handles are fictional; the
 * phone numbers use the 0917-555-xxxx range, which is not a live block.
 */

export interface DemoAccount {
  trustclubId: string
  displayName: string
  municipality: string
  phone?: string
  viber?: string
  facebook?: string
  isStaff?: boolean
}

export interface DemoListing {
  owner: string
  category: string
  type: 'SELL' | 'RENT' | 'SERVICE'
  title: string
  price: number | null
  unit: 'TOTAL' | 'PER_HOUR' | 'PER_DAY' | 'PER_WEEK' | 'PER_MONTH' | 'PER_JOB' | 'QUOTE'
  negotiable?: boolean
  municipality: string
  barangay?: string
  description: string
  attributes: Record<string, string | number | boolean>
  daysAgo: number
  status?: 'ACTIVE' | 'RESERVED' | 'CLOSED'
  /** Filenames under /public/demo. See public/demo/CREDITS.md — these are
      freely licensed stand-ins, NOT photos of the listed items. */
  images?: string[]
}

export const DEMO_ACCOUNTS: DemoAccount[] = [
  { trustclubId: 'juan.santos', displayName: 'Juan Santos', municipality: 'San Ildefonso', phone: '+639175550101' },
  { trustclubId: 'ruben.dlc', displayName: "Mang Ruben's Rentals", municipality: 'San Ildefonso', phone: '+639175550102', viber: '+639175550102' },
  { trustclubId: 'marites.g', displayName: 'Marites Garcia', municipality: 'San Ildefonso', phone: '+639175550103' },
  { trustclubId: 'boyet.motors', displayName: 'Boyet Motorworks', municipality: 'San Ildefonso', phone: '+639175550104' },
  { trustclubId: 'lito.reyes', displayName: 'Lito Reyes', municipality: 'San Ildefonso', phone: '+639175550105' },
  { trustclubId: 'ana.cruz', displayName: 'Ana Cruz', municipality: 'San Ildefonso', phone: '+639175550106' },
  { trustclubId: 'nene.sari', displayName: "Nene's Sari-sari", municipality: 'San Ildefonso', phone: '+639175550107' },
  { trustclubId: 'edgar.p', displayName: 'Edgar Pascual', municipality: 'San Ildefonso', phone: '+639175550108' },
  { trustclubId: 'jm.tech', displayName: 'JM Gadgets', municipality: 'San Ildefonso', phone: '+639175550109', facebook: 'https://facebook.com/jmgadgetsph' },
  { trustclubId: 'tessie.b', displayName: 'Tessie Bautista', municipality: 'San Ildefonso', phone: '+639175550110' },
  { trustclubId: 'noel.aircon', displayName: 'Noel Aircon Services', municipality: 'San Ildefonso', phone: '+639175550111', viber: '+639175550111' },
  { trustclubId: 'rico.hauling', displayName: 'Rico Hauling', municipality: 'San Ildefonso', phone: '+639175550112' },
  { trustclubId: 'dely.farm', displayName: 'Dely Farm Supply', municipality: 'San Ildefonso', phone: '+639175550113' },
  { trustclubId: 'toto.welding', displayName: 'Toto Welding Shop', municipality: 'San Ildefonso', phone: '+639175550114' },
  { trustclubId: 'grace.l', displayName: 'Grace Lim', municipality: 'San Ildefonso', phone: '+639175550115' },
  { trustclubId: 'benjie.r', displayName: 'Benjie Ramos', municipality: 'San Ildefonso', phone: '+639175550116' },
  { trustclubId: 'lorna.catering', displayName: 'Lorna Catering Services', municipality: 'San Ildefonso', phone: '+639175550117', facebook: 'https://facebook.com/lornacateringlaguna' },
  { trustclubId: 'dado.trike', displayName: 'Dado Mercado', municipality: 'San Ildefonso', phone: '+639175550118' },
  { trustclubId: 'weng.h', displayName: 'Weng Hernandez', municipality: 'San Ildefonso', phone: '+639175550119' },
  { trustclubId: 'ferdie.c', displayName: 'Ferdie Carandang', municipality: 'San Ildefonso', phone: '+639175550120' },
  { trustclubId: 'mylene.s', displayName: 'Mylene Soriano', municipality: 'San Ildefonso', phone: '+639175550121' },
  { trustclubId: 'kap.tolits', displayName: 'Tolits Villanueva', municipality: 'San Ildefonso', phone: '+639175550122' },
  { trustclubId: 'jhun.tutor', displayName: 'Jhun Delos Reyes', municipality: 'San Ildefonso', phone: '+639175550123' },
  { trustclubId: 'kl-staff', displayName: 'KantoList Staff', municipality: 'San Ildefonso', isStaff: true },
  { trustclubId: 'aling.baby', displayName: "Aling Baby's Rice Store", municipality: 'San Ildefonso', phone: '+639175550124' },
  { trustclubId: 'joy.nails', displayName: 'Joy Nail Art', municipality: 'San Ildefonso', phone: '+639175550125', viber: '+639175550125' },
  { trustclubId: 'mang.tino', displayName: 'Mang Tino Vegetables', municipality: 'San Ildefonso', phone: '+639175550126' },
  { trustclubId: 'sunshine.laundry', displayName: 'Sunshine Laundry Shop', municipality: 'San Ildefonso', phone: '+639175550127' },
  { trustclubId: 'kuya.jhon', displayName: 'Kuya Jhon Videoke Rental', municipality: 'San Ildefonso', phone: '+639175550128' },
  { trustclubId: 'rr.printing', displayName: 'RR Tarpaulin & Printing', municipality: 'San Ildefonso', phone: '+639175550129', facebook: 'https://facebook.com/rrprintingcalamba' },
  { trustclubId: 'nanay.rose', displayName: 'Nanay Rose Kakanin', municipality: 'San Ildefonso', phone: '+639175550130' },
  { trustclubId: 'aqua.pure', displayName: 'AquaPure Water Station', municipality: 'San Ildefonso', phone: '+639175550131', viber: '+639175550131' },
  { trustclubId: 'thrift.ph', displayName: 'Thrift Finds by Kim', municipality: 'San Ildefonso', phone: '+639175550132' },
  { trustclubId: 'barber.dan', displayName: "Dan's Barbershop", municipality: 'San Ildefonso', phone: '+639175550133' },
  { trustclubId: 'teacher.mia', displayName: 'Teacher Mia', municipality: 'San Ildefonso', phone: '+639175550134' },
  { trustclubId: 'aling.puring', displayName: 'Aling Puring Fish Vendor', municipality: 'San Ildefonso', phone: '+639175550135' },
  { trustclubId: 'jomar.gas', displayName: 'Jomar LPG Delivery', municipality: 'San Ildefonso', phone: '+639175550136' },
  { trustclubId: 'tita.beth', displayName: 'Tita Beth Baby Shop', municipality: 'San Ildefonso', phone: '+639175550137' },
  { trustclubId: 'hilot.remy', displayName: 'Remy Hilot & Massage', municipality: 'San Ildefonso', phone: '+639175550138' },
]

const USED = 'Used'
const NEW = 'Brand new'

export const DEMO_LISTINGS: DemoListing[] = [
  // ---- Motorcycles ----

  // ---- Bicycles ----
  { owner: 'ana.cruz', category: 'bicycle', type: 'SELL', title: 'Mountain bike 26", 21-speed', price: 4500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 12,
    description: 'Working condition, brakes recently serviced. Small scratches on the frame. Good starter MTB for going around the barangay.',
    attributes: { bike_type: 'Mountain', frame_size: 'M', wheel_size_in: 26, condition: USED }, images: ["bike.jpg"] },
  { owner: 'jm.tech', category: 'bicycle', type: 'SELL', title: 'Folding bike 20", almost new', price: 6800, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 7,
    description: 'Used less than ten times. Folds small enough for a car trunk or a jeep. Complete with bag.',
    attributes: { bike_type: 'Folding', frame_size: 'S', wheel_size_in: 20, condition: USED } },
  { owner: 'tessie.b', category: 'bicycle', type: 'SELL', title: "Kids' BMX 16\", 4 to 7 years old", price: 2200, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 16,
    description: 'Outgrown by my son. Still solid, with training wheels included if you need them.',
    attributes: { bike_type: 'Kids', wheel_size_in: 16, condition: USED } },
  { owner: 'weng.h', category: 'bicycle', type: 'SELL', title: 'E-bike, 3 months old, with charger', price: 24000, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 3,
    description: 'Battery still strong, around 35 km per full charge. Selling because I bought a motorcycle. Charger and spare key included.',
    attributes: { bike_type: 'E-bike', frame_size: 'M', wheel_size_in: 26, condition: USED } },

  // ---- Tricycles ----

  // ---- Phones and tablets ----
  { owner: 'jm.tech', category: 'phone-tablet', type: 'SELL', title: 'Samsung Galaxy A15 5G, 128GB, complete', price: 7800, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 2,
    description: 'Openline, no issues. Complete with box, charger and receipt. Warranty until June. Meet up at Nuvali or Sta. Rosa.',
    attributes: { brand: 'Samsung', model: 'Galaxy A15 5G', storage_gb: 128, condition: USED, with_box: true } },
  { owner: 'ana.cruz', category: 'phone-tablet', type: 'SELL', title: 'iPhone 11 64GB, battery 82%', price: 12500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4,
    description: 'Factory unlocked, no iCloud lock. Battery health 82 percent, still lasts a full day with normal use. Small scratch on the back, screen is clean.',
    attributes: { brand: 'Apple', model: 'iPhone 11', storage_gb: 64, condition: USED, with_box: false } },
  { owner: 'jm.tech', category: 'phone-tablet', type: 'SELL', title: 'Xiaomi Redmi 13C, brand new sealed', price: 5299, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 1,
    description: 'Brand new and sealed, official Xiaomi warranty. We have stocks in blue and black. Cash on meet-up or GCash before delivery.',
    attributes: { brand: 'Xiaomi', model: 'Redmi 13C', storage_gb: 128, condition: NEW, with_box: true } },
  { owner: 'tessie.b', category: 'phone-tablet', type: 'SELL', title: 'Realme C55 8/256, 6 months used', price: 6200, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 9,
    description: 'Used for six months, no scratches, always in a case. Complete with box and original charger.',
    attributes: { brand: 'Realme', model: 'C55', storage_gb: 256, condition: USED, with_box: true } },
  { owner: 'weng.h', category: 'phone-tablet', type: 'SELL', title: 'Samsung Tab A8 for online class', price: 6500, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 18,
    description: 'Used by my daughter for online class, not needed anymore. Screen has no cracks. With keyboard case.',
    attributes: { brand: 'Samsung', model: 'Galaxy Tab A8', storage_gb: 64, condition: USED, with_box: false } },
  { owner: 'benjie.r', category: 'phone-tablet', type: 'SELL', title: 'Oppo A17 with issue, for parts', price: 1500, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 27,
    description: 'Screen is cracked and touch does not work on the left side. Everything else is fine. Selling for parts or for someone who can repair it.',
    attributes: { brand: 'Oppo', model: 'A17', storage_gb: 64, condition: 'For parts', with_box: false } },
  { owner: 'mylene.s', category: 'phone-tablet', type: 'SELL', title: 'Infinix Hot 40i, 8/256, still warranty', price: 5800, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 21, status: 'CLOSED',
    description: 'Sold already, thank you. Leaving this up so people can see the price.',
    attributes: { brand: 'Infinix', model: 'Hot 40i', storage_gb: 256, condition: USED, with_box: true } },
  { owner: 'juan.santos', category: 'phone-tablet', type: 'SELL', title: 'Vivo Y17s 6/128, complete package', price: 5900, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 7,
    description: 'Complete with box, charger, and free tempered glass and case. Used for four months only.',
    attributes: { brand: 'Vivo', model: 'Y17s', storage_gb: 128, condition: USED, with_box: true } },

  // ---- Laptops and computers ----

  // ---- Sound and lights ----

  // ---- Appliances ----
  { owner: 'tessie.b', category: 'appliances', type: 'SELL', title: 'Inverter aircon 1.0 HP, 2 years used', price: 12500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 6,
    description: 'Cools fast and saves on electricity. Cleaned regularly. Selling because we moved to a smaller room. Buyer arranges the dismantling.',
    attributes: { appliance_type: 'Air conditioner', brand: 'Carrier', condition: USED } },
  { owner: 'nene.sari', category: 'appliances', type: 'SELL', title: 'Chest freezer 7 cu ft, for business', price: 14000, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 11,
    description: 'Used in our sari-sari store for ice and frozen goods. Still freezes well. Selling because we bought a bigger one.',
    attributes: { appliance_type: 'Freezer', brand: 'Fujidenzo', condition: USED } },
  { owner: 'ana.cruz', category: 'appliances', type: 'SELL', title: 'Washing machine twin tub 8kg', price: 4800, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 15,
    description: 'Twin tub, spinner working. Some rust on the legs but it does not affect use.',
    attributes: { appliance_type: 'Washing machine', brand: 'Whirlpool', condition: USED } },
  { owner: 'weng.h', category: 'appliances', type: 'SELL', title: 'Rice cooker and gas stove, take all', price: 1800, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 25,
    description: 'Take all price for both. Moving out, everything must go this week.',
    attributes: { appliance_type: 'Kitchen', condition: USED } },
  { owner: 'mylene.s', category: 'appliances', type: 'SELL', title: 'Smart TV 43 inch, brand new', price: 13900, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 3,
    description: 'Brand new in box, unwanted raffle prize. Netflix and YouTube built in. With warranty card.',
    attributes: { appliance_type: 'Television', brand: 'TCL', condition: NEW } },
  { owner: 'benjie.r', category: 'appliances', type: 'SELL', title: 'Electric fan stand type, 2 units', price: 900, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 28,
    description: 'Two stand fans, both working. ₱450 each or ₱900 for both.',
    attributes: { appliance_type: 'Electric fan', condition: USED } },

  // ---- Tools and equipment ----
  { owner: 'toto.welding', category: 'power-tools', type: 'SELL', title: 'Welding machine 300A, heavy duty', price: 8500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 9,
    description: 'Inverter type welding machine, used in our shop. Comes with cables and holder. Still strong for 6013 rods.',
    attributes: { tool_type: 'Welding', brand: 'Ingco', power_w: 7000, condition: USED } },
  { owner: 'ferdie.c', category: 'power-tools', type: 'RENT', title: 'Generator 5kva for rent, events or brownout', price: 1200, unit: 'PER_DAY',
    municipality: 'San Ildefonso', daysAgo: 13,
    description: 'Good for events or during long brownouts. Fuel not included. Delivery within San Ildefonso is free.',
    attributes: { tool_type: 'Generator', brand: 'Kawasaki', power_w: 5000, condition: USED } },
  { owner: 'edgar.p', category: 'power-tools', type: 'SELL', title: 'Water pump 1HP, jetmatic replacement', price: 3400, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 18,
    description: 'Used for one planting season only. Still strong suction. With hose.',
    attributes: { tool_type: 'Water pump', brand: 'Kaisar', power_w: 750, condition: USED } },
  { owner: 'toto.welding', category: 'power-tools', type: 'SELL', title: 'Angle grinder and drill, take all', price: 2400, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 21,
    description: 'Both working, used in construction. Take all price. Extra discs included.',
    attributes: { tool_type: 'Power tools', brand: 'Bosch', power_w: 900, condition: USED } },

  // ---- Furniture ----
  { owner: 'tessie.b', category: 'furniture', type: 'SELL', title: 'Narra dining set, 6 seaters', price: 15000, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 10,
    description: 'Solid narra, inherited from my parents. Heavy and sturdy. Needs light refinishing. Buyer arranges pick-up.',
    attributes: { furniture_type: 'Dining set', material: 'Wood', condition: USED } },
  { owner: 'grace.l', category: 'furniture', type: 'SELL', title: 'Double deck bed with mattress', price: 6500, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 16,
    description: 'Metal frame double deck, good for a boarding house. Two mattresses included, still clean.',
    attributes: { furniture_type: 'Bed', material: 'Metal', condition: USED } },
  { owner: 'nene.sari', category: 'furniture', type: 'SELL', title: 'Rattan sofa set with cushions', price: 8000, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 20,
    description: 'Classic rattan set, three seater plus two chairs and a table. Cushions were re-covered last year.',
    attributes: { furniture_type: 'Sofa set', material: 'Rattan', condition: USED } },
  { owner: 'juan.santos', category: 'furniture', type: 'SELL', title: 'Office table and chair, home office', price: 3200, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 29,
    description: 'Used for work from home. Table has one drawer, chair is adjustable. No damage.',
    attributes: { furniture_type: 'Office table', material: 'Wood', condition: USED } },

  // ---- Services: repair ----
  { owner: 'boyet.motors', category: 'repair', type: 'SERVICE', title: 'Motorcycle repair and tune-up, home service', price: 300, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 7,
    description: 'Change oil, tune-up, electrical and brake work. Home service within San Ildefonso, or drop off at the shop near the public market. Parts are charged separately.',
    attributes: { specialty: 'Motorcycle', home_service: true }, images: ["repair.jpg"] },
  { owner: 'noel.aircon', category: 'repair', type: 'SERVICE', title: 'Aircon cleaning and repair, window or split', price: 700, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4,
    description: 'General cleaning for window type is ₱700, split type ₱1,200. Freon charging and repair also available. We cover San Ildefonso.',
    attributes: { specialty: 'Aircon', home_service: true } },
  { owner: 'jm.tech', category: 'repair', type: 'SERVICE', title: 'Cellphone repair, screen and charging port', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 12,
    description: 'Screen replacement, charging port, battery and software problems. Price depends on the model and parts — send me the model and a photo for a quote.',
    attributes: { specialty: 'Phone', home_service: false } },
  { owner: 'edgar.p', category: 'repair', type: 'SERVICE', title: 'Appliance repair — ref, washing machine, fan', price: 500, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 19,
    description: 'Twenty years experience. Check-up fee ₱500, deducted from the total if you proceed with the repair. Home service around San Ildefonso.',
    attributes: { specialty: 'Appliance', home_service: true } },
  { owner: 'kap.tolits', category: 'repair', type: 'SERVICE', title: 'House wiring and electrical repair', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 24,
    description: 'Licensed electrician. New wiring, additional outlets, breaker problems and meter applications. Free estimate within San Ildefonso.',
    attributes: { specialty: 'Electrical', home_service: true } },

  // ---- Services: construction ----
  { owner: 'toto.welding', category: 'construction', type: 'SERVICE', title: 'Welding works — grills, gates, railings', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 6,
    description: 'Window grills, gates, railings and steel trusses. Send the measurements for a quote. We fabricate in the shop and install on site.',
    attributes: { trade: 'Welder', crew_size: 3 } },
  { owner: 'kap.tolits', category: 'construction', type: 'SERVICE', title: 'Mason and finishing works, per day', price: 800, unit: 'PER_DAY',
    municipality: 'San Ildefonso', daysAgo: 11,
    description: 'Tile setting, plastering, concrete works. ₱800 per day per mason plus helper at ₱550. Minimum three days.',
    attributes: { trade: 'Mason', crew_size: 4 } },
  { owner: 'ferdie.c', category: 'construction', type: 'SERVICE', title: 'House painting, interior and exterior', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 17,
    description: 'Painting for houses and small buildings. Labor only or with materials. Free estimate — send the floor area and how many coats you want.',
    attributes: { trade: 'Painter', crew_size: 3 } },
  { owner: 'benjie.r', category: 'construction', type: 'SERVICE', title: 'Carpentry — cabinets, doors, repairs', price: 750, unit: 'PER_DAY',
    municipality: 'San Ildefonso', daysAgo: 22,
    description: 'Built-in cabinets, doors, ceiling and general carpentry. Daily rate for labor, materials on your account.',
    attributes: { trade: 'Carpenter', crew_size: 2 } },

  // ---- Services: transport ----

  // ---- Services: events and food ----
  { owner: 'lorna.catering', category: 'events-food', type: 'SERVICE', title: 'Catering for birthdays and weddings', price: 350, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 2,
    description: 'Package starts at ₱350 per head for four dishes, rice and drinks. Includes tables, chairs and skirting. Fifty pax minimum. Book two weeks ahead for weekends.',
    attributes: { event_type: 'Catering', capacity_pax: 300 } },
  { owner: 'lorna.catering', category: 'events-food', type: 'SERVICE', title: 'Lechon baboy, whole, for orders', price: 8500, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 9,
    description: 'Whole lechon, around 30 to 35 kilos, good for 40 to 50 people. Order two days ahead. Delivery within San Ildefonso is free.',
    attributes: { event_type: 'Lechon', capacity_pax: 50 } },
  { owner: 'mylene.s', category: 'events-food', type: 'SERVICE', title: 'Photo and video coverage for events', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 15,
    description: 'Birthdays, weddings, christenings and debut. Packages include edited photos and a highlight video. Message me for the rate card and available dates.',
    attributes: { event_type: 'Photo / video', capacity_pax: 200 } },
  { owner: 'nene.sari', category: 'events-food', type: 'SERVICE', title: 'Palabok and pancit trays for orders', price: 900, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 23,
    description: 'Large tray good for 15 to 20 persons. Palabok, pancit bihon or sotanghon. Order one day ahead. Pick up at the store.',
    attributes: { event_type: 'Catering', capacity_pax: 20 } },

  // ---- Farm and animals ----
  { owner: 'dely.farm', category: 'livestock', type: 'SELL', title: 'Native chickens, ready to lay', price: 450, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4,
    description: 'Native hens, around six months old, ready to lay. ₱450 each, discount if you take five or more. Healthy and free range.',
    attributes: { animal: 'Chicken', breed: 'Native', quantity: 20 } },
  { owner: 'dely.farm', category: 'livestock', type: 'SELL', title: 'Goats for sale, male and female', price: 6500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 12,
    description: 'Anglo-Nubian cross, healthy and dewormed. Price is per head depending on size. You can visit the farm to see them.',
    attributes: { animal: 'Goat', breed: 'Anglo-Nubian cross', quantity: 8 } },
  { owner: 'ferdie.c', category: 'livestock', type: 'SELL', title: 'Fattener pigs, around 90kg', price: 14000, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 18,
    description: 'Ready for slaughter, around 90 to 100 kilos. Price per head. We can arrange delivery within Bulacan for a fee.',
    attributes: { animal: 'Pig', breed: 'Landrace cross', quantity: 6 } },
  { owner: 'edgar.p', category: 'livestock', type: 'SELL', title: 'Itik ducks with eggs, take all', price: 3500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 25,
    description: 'Ten laying ducks, take all price. Good for balut or salted eggs business. Selling because I have no time to care for them.',
    attributes: { animal: 'Duck', breed: 'Itik', quantity: 10 } },
  { owner: 'dely.farm', category: 'farm-supplies', type: 'SELL', title: 'Hog feeds and chicken feeds, per sack', price: 1450, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 6,
    description: 'Grower and finisher feeds, 50 kg per sack. Prices change weekly, message for the current rate. Delivery for five sacks and up.',
    attributes: { supply_type: 'Feeds' } },
  { owner: 'dely.farm', category: 'farm-supplies', type: 'SELL', title: 'Coconut and calamansi seedlings', price: 120, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 16,
    description: 'Healthy seedlings from our nursery. Calamansi at ₱120, coconut at ₱180. Bulk discount for 50 pieces and up.',
    attributes: { supply_type: 'Seedlings' } },
  { owner: 'kap.tolits', category: 'farm-supplies', type: 'SELL', title: 'Knapsack sprayer 16L, almost new', price: 1600, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 27,
    description: 'Manual knapsack sprayer, used twice. No leaks. Spare nozzle included.',
    attributes: { supply_type: 'Equipment' } },

  // ---- Rice, produce and food ----
  { owner: 'aling.baby', category: 'rice-grains', type: 'SELL', title: 'Sinandomeng rice, 25kg sack', price: 1550, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 1, images: ['rice.jpg'],
    description: 'Fresh stock, well-milled Sinandomeng. ₱1,550 per 25kg sack, ₱62 per kilo if you buy retail. Free delivery within San Ildefonso for two sacks and up. Price changes weekly, message for today’s rate.',
    attributes: { variety: 'Sinandomeng', pack_kg: 25, delivery: true } },
  { owner: 'aling.baby', category: 'rice-grains', type: 'SELL', title: 'Dinorado rice, 50kg sack, wholesale', price: 3100, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4, images: ['rice.jpg'],
    description: 'For carinderia, canteen or resellers. Dinorado, malinis at mabango. Wholesale price for five sacks and up. We deliver anywhere in Bulacan for a small fee.',
    attributes: { variety: 'Dinorado', pack_kg: 50, delivery: true } },
  { owner: 'aling.baby', category: 'rice-grains', type: 'SELL', title: 'Brown rice, 5kg pack, organic', price: 420, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 9, images: ['rice.jpg'],
    description: 'Unpolished brown rice from a local farm in San Ildefonso. Good for diabetics and diet. 5kg resealable pack.',
    attributes: { variety: 'Brown rice', pack_kg: 5, delivery: false } },
  { owner: 'mang.tino', category: 'vegetables-fruits', type: 'SELL', title: 'Fresh vegetables — pinakbet mix, per kilo', price: 90, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 1, images: ['vegetables.jpg'],
    description: 'Talong, okra, ampalaya, sitaw, kalabasa. Harvested every morning from our own farm. Order before 6am for same-day delivery around San Ildefonso.',
    attributes: { produce: 'Pinakbet mix', sold_by: 'Per kilo', organic: false } },
  { owner: 'mang.tino', category: 'vegetables-fruits', type: 'SELL', title: 'Saba banana per bundle, sweet', price: 120, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 3, images: ['bananas.jpg'],
    description: 'Saging na saba, good for turon, banana cue or minatamis. Around 12 to 15 pieces per bundle. Bulk price for sellers.',
    attributes: { produce: 'Saba banana', sold_by: 'Per bundle', organic: false } },
  { owner: 'mang.tino', category: 'vegetables-fruits', type: 'SELL', title: 'Organic lettuce and herbs, hydroponic', price: 180, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 6, images: ['vegetables.jpg'],
    description: 'Romaine, lollo rosa, basil and mint. Grown hydroponically without pesticides. Per kilo price, minimum half a kilo.',
    attributes: { produce: 'Lettuce and herbs', sold_by: 'Per kilo', organic: true } },
  { owner: 'dely.farm', category: 'vegetables-fruits', type: 'SELL', title: 'Buko and mature coconut, per piece', price: 35, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 8, images: ['coconut.jpg'],
    description: 'Buko for juice at ₱35, mature coconut for gata at ₱25. We can deliver by the sack for buko shops and carinderia.',
    attributes: { produce: 'Coconut', sold_by: 'Per piece', organic: false } },
  { owner: 'ferdie.c', category: 'vegetables-fruits', type: 'SELL', title: 'Lanzones, sweet, per kilo — in season', price: 130, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 2, images: ['bananas.jpg'],
    description: 'San Ildefonso lanzones, matamis at hindi mapakla. In season now. Order by the kilo or by the kaing for resellers.',
    attributes: { produce: 'Lanzones', sold_by: 'Per kilo', organic: false } },
  { owner: 'nanay.rose', category: 'homemade-food', type: 'SELL', title: 'Kakanin — suman, biko, kutsinta by the tray', price: 350, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 2, images: ['catering.jpg'],
    description: 'Bilao of assorted kakanin: suman, biko, kutsinta and sapin-sapin. Good for merienda for 15 to 20 people. Order one day ahead. Pick up in San Ildefonso or delivery for orders of three bilao and up.',
    attributes: { food_type: 'Kakanin & delicacies', order_ahead_days: 1 } },
  { owner: 'nanay.rose', category: 'homemade-food', type: 'SELL', title: 'Homemade peanut butter, no preservatives', price: 180, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 7, images: ['catering.jpg'],
    description: 'Pure peanut, walang halong kung ano-ano. 500ml jar. Chunky or smooth, sabihin lang kung alin.',
    attributes: { food_type: 'Peanut butter & spreads', order_ahead_days: 0 } },
  { owner: 'nanay.rose', category: 'homemade-food', type: 'SELL', title: 'Frozen siomai and lumpia, for resellers', price: 250, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 12, images: ['catering.jpg'],
    description: 'Fifty pieces per pack. Pork siomai or lumpiang shanghai. Good for resellers and canteens, may discount kapag maramihan.',
    attributes: { food_type: 'Frozen goods', order_ahead_days: 2 } },
  { owner: 'lorna.catering', category: 'homemade-food', type: 'SELL', title: 'Birthday cake, custom design', price: 850, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 5, images: ['catering.jpg'],
    description: 'Chiffon or moist chocolate, 8 inches round. Custom design and message included. Order three days ahead, one week for fondant designs.',
    attributes: { food_type: 'Baked goods', order_ahead_days: 3 } },
  { owner: 'aling.puring', category: 'fish-meat', type: 'SELL', title: 'Fresh tilapia from the lake, per kilo', price: 160, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 1, images: ['fish.jpg'],
    description: 'Buhay pa pagdating, straight from the fish pen. ₱160 per kilo, ₱150 if you take three kilos or more. I am at the public market every morning until 10am.',
    attributes: { source: 'Fresh fish', sold_by: 'Per kilo' } },
  { owner: 'aling.puring', category: 'fish-meat', type: 'SELL', title: 'Tuyo and daing, dried fish assorted', price: 240, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 10, images: ['fish.jpg'],
    description: 'Tuyong galunggong, danggit and dilis. Per kilo price. Sun-dried, hindi masyadong maalat.',
    attributes: { source: 'Dried fish', sold_by: 'Per kilo' } },
  { owner: 'ferdie.c', category: 'fish-meat', type: 'SELL', title: 'Native chicken, dressed, per kilo', price: 280, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 6, images: ['chicken.jpg'],
    description: 'Free range native chicken, dressed and cleaned. Good for tinola and adobo. Order a day ahead so it is fresh.',
    attributes: { source: 'Chicken', sold_by: 'Per kilo' } },

  // ---- Beauty and wellness ----
  { owner: 'joy.nails', category: 'beauty-wellness', type: 'SERVICE', title: 'Gel manicure and pedicure, home service', price: 550, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 1, images: ['nails.jpg'],
    description: 'Gel polish mani and pedi, lasts three to four weeks. ₱550 for both, ₱300 for hands only. Home service within San Ildefonso, ₱100 extra for nearby towns. Free design for two nails.',
    attributes: { beauty_service: 'Gel nails', home_service: true } },
  { owner: 'joy.nails', category: 'beauty-wellness', type: 'SERVICE', title: 'Eyelash extension, classic and volume', price: 700, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 5, images: ['nails.jpg'],
    description: 'Classic set ₱700, volume ₱1,100. Refill within three weeks is half price. Home service or at my place in Real.',
    attributes: { beauty_service: 'Eyelash extension', home_service: true } },
  { owner: 'barber.dan', category: 'beauty-wellness', type: 'SERVICE', title: 'Haircut for men and kids, walk-in', price: 120, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 3, images: ['barber.jpg'],
    description: 'Regular haircut ₱120, kids ₱100, with shave ₱160. Open 9am to 8pm, closed Mondays. Walk-in lang, no need to book.',
    attributes: { beauty_service: 'Haircut', home_service: false } },
  { owner: 'mylene.s', category: 'beauty-wellness', type: 'SERVICE', title: 'Bridal and event make-up', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 8, images: ['nails.jpg'],
    description: 'Make-up for weddings, debut and photoshoots. Includes hairstyling. Rate depends on the number of people and the venue — message me your date to check availability.',
    attributes: { beauty_service: 'Make-up', home_service: true } },
  { owner: 'hilot.remy', category: 'beauty-wellness', type: 'SERVICE', title: 'Hilot and body massage, home service', price: 400, unit: 'PER_HOUR', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4, images: ['massage.jpg'],
    description: 'Traditional hilot for pasma, lamig and body pain. One hour ₱400, one and a half hours ₱550. Twenty years experience. I can come to your house within San Ildefonso.',
    attributes: { beauty_service: 'Massage / hilot', home_service: true } },
  { owner: 'weng.h', category: 'beauty-wellness', type: 'SERVICE', title: 'Hair rebond and color, salon quality', price: 1800, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 11, images: ['barber.jpg'],
    description: 'Rebond starts at ₱1,800 depending on hair length. Hair color ₱900. Using branded products, hindi mumurahin. Booking required.',
    attributes: { beauty_service: 'Hair color / rebond', home_service: false } },

  // ---- Laundry ----

  // ---- Printing and signage ----
  { owner: 'rr.printing', category: 'printing', type: 'SERVICE', title: 'Tarpaulin printing — ₱15 per square foot', price: 15, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 1, images: ['printing.jpg'],
    description: 'Birthday, wedding, business signage and campaign tarps. ₱15 per square foot, with eyelets. Free layout if you already have the design. Same-day for orders before 12nn.',
    attributes: { print_type: 'Tarpaulin', rush: true } },
  { owner: 'rr.printing', category: 'printing', type: 'SERVICE', title: 'T-shirt printing, minimum 10 pieces', price: 180, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 6, images: ['printing.jpg'],
    description: 'DTF printing on cotton shirts. ₱180 per piece including the shirt for a small design, minimum ten pieces. Good for team uniforms, reunions and barangay events.',
    attributes: { print_type: 'T-shirt printing', rush: false } },
  { owner: 'rr.printing', category: 'printing', type: 'SERVICE', title: 'Invitations, giveaways and photo booth', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 13, images: ['printing.jpg'],
    description: 'Wedding and debut invitations, personalised giveaways, and photo booth rental for events. Send me your theme and headcount for a package quote.',
    attributes: { print_type: 'Invitations & giveaways', rush: false } },
  { owner: 'jm.tech', category: 'printing', type: 'SERVICE', title: 'Photocopy, printing and lamination', price: 2, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 20, images: ['printing.jpg'],
    description: 'Photocopy ₱2 per page, colored print ₱10, lamination ₱25. Also typing and encoding services for resume and school work.',
    attributes: { print_type: 'Photocopy & documents', rush: true } },

  // ---- Tutoring ----

  // ---- Water and LPG ----
  { owner: 'aqua.pure', category: 'water-lpg', type: 'SERVICE', title: 'Purified water delivery — ₱30 per gallon', price: 30, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 2, images: ['water.jpg'],
    description: 'Round gallon ₱30, slim ₱35. Free delivery for three gallons and up within San Ildefonso. Same-day if you order before 4pm. We also sell new containers.',
    attributes: { delivery_type: 'Purified water', free_delivery: true } },
  { owner: 'jomar.gas', category: 'water-lpg', type: 'SERVICE', title: 'LPG tank delivery, 11kg — refill or new', price: 950, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4, images: ['lpg.jpg'],
    description: 'Refill 11kg ₱950, brand new tank with content ₱2,400. Delivered to your door within San Ildefonso. We check the regulator and hose for free.',
    attributes: { delivery_type: 'LPG tank', free_delivery: true } },
  { owner: 'nene.sari', category: 'water-lpg', type: 'SERVICE', title: 'Water and LPG delivery, San Ildefonso area', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 15, images: ['water.jpg'],
    description: 'Both purified water and LPG. Price depends on what you need and where you are. Text or call, we deliver from 7am to 7pm.',
    attributes: { delivery_type: 'Both water and LPG', free_delivery: false } },

  // ---- Clothes, shoes, baby ----
  { owner: 'thrift.ph', category: 'clothes', type: 'SELL', title: 'Ukay-ukay bale, assorted ladies tops', price: 3500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 3, images: ['ukay.jpg'],
    description: 'Class A bale, around 100 pieces of ladies tops. For resellers who want to start their own ukay stall. You can inspect before paying.',
    attributes: { clothing_type: 'Bale / bulk ukay', size: 'Assorted', gender: 'Women', condition: 'Used' } },
  { owner: 'thrift.ph', category: 'clothes', type: 'SELL', title: 'Preloved dresses, ₱150 each, take all discount', price: 150, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 6, images: ['ukay.jpg'],
    description: 'Casual and semi-formal dresses, sizes S to L. ₱150 each or ₱1,200 for ten. All washed and pressed already. Meet up at Sta. Rosa or ship via J&T.',
    attributes: { clothing_type: 'Dresses', size: 'Assorted', gender: 'Women', condition: 'Used' } },
  { owner: 'tessie.b', category: 'clothes', type: 'SELL', title: 'School uniform, elementary, barely used', price: 250, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 16, images: ['ukay.jpg'],
    description: 'Complete set, size 8. Used for one school year only, no stains. Selling because my daughter moved schools.',
    attributes: { clothing_type: 'Uniform', size: 'S', gender: 'Kids', condition: 'Used' } },
  { owner: 'thrift.ph', category: 'shoes-bags', type: 'SELL', title: 'Preloved sneakers, size 40 to 43', price: 450, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 5, images: ['shoes.jpg'],
    description: 'Assorted branded sneakers, cleaned already. Sizes 40 to 43 available. ₱450 each, ₱800 for two pairs.',
    attributes: { item_type: 'Sneakers', shoe_size: 42, condition: 'Used' } },
  { owner: 'tita.beth', category: 'shoes-bags', type: 'SELL', title: 'Black school shoes, size 32, brand new', price: 380, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 12, images: ['shoes.jpg'],
    description: 'Brand new with box, wrong size ang nabili. Leather-type, good for school. Fixed price na po.',
    attributes: { item_type: 'School shoes', shoe_size: 32, condition: 'Brand new' } },
  { owner: 'tita.beth', category: 'baby-items', type: 'SELL', title: 'Baby stroller, foldable, good condition', price: 2200, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 4, images: ['baby.jpg'],
    description: 'Reclining stroller with canopy and basket. Wheels smooth, no damage. Cleaned and disinfected. Outgrown by my son.',
    attributes: { baby_item: 'Stroller', condition: 'Used' } },
  { owner: 'tita.beth', category: 'baby-items', type: 'SELL', title: 'Wooden crib with mattress', price: 3500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 11, images: ['baby.jpg'],
    description: 'Solid wood crib, adjustable height, with foam mattress. Some marks on the rails but sturdy pa rin. Buyer picks up.',
    attributes: { baby_item: 'Crib', condition: 'Used' } },
  { owner: 'ana.cruz', category: 'baby-items', type: 'SELL', title: 'Baby walker and high chair, take all', price: 1500, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 19, images: ['baby.jpg'],
    description: 'Take all price for both. Walker has music, high chair has a removable tray. Complete and working.',
    attributes: { baby_item: 'Walker', condition: 'Used' } },

  // ---- More rentals and services people actually look for ----
  { owner: 'lorna.catering', category: 'events-food', type: 'RENT', title: 'Tables, chairs and tents for rent', price: 25, unit: 'PER_DAY', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 11, images: ['catering.jpg'],
    description: 'Monobloc chairs ₱25 each, round tables ₱250, 3x3 tent ₱800. Delivery and pick-up included within San Ildefonso. Good for birthdays, wakes and barangay events.',
    attributes: { event_type: 'Catering', capacity_pax: 200 } },
  { owner: 'mylene.s', category: 'events-food', type: 'RENT', title: 'Balloon and backdrop styling for parties', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 14, images: ['catering.jpg'],
    description: 'Balloon arch, backdrop and simple styling for birthdays and christenings. Packages from ₱3,500. Send me your theme and venue size.',
    attributes: { event_type: 'Host', capacity_pax: 100 } },
  { owner: 'noel.aircon', category: 'repair', type: 'SERVICE', title: 'Refrigerator and freezer repair', price: 600, unit: 'PER_JOB', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 9, images: ['fridge.jpg'],
    description: 'Not cooling, leaking, or noisy compressor. Check-up ₱600, deducted from the repair if you push through. Freon charging and compressor replacement available.',
    attributes: { specialty: 'Appliance', home_service: true } },
  { owner: 'boyet.motors', category: 'repair', type: 'SERVICE', title: 'Tire vulcanizing and patch, 24 hours', price: 80, unit: 'PER_JOB',
    municipality: 'San Ildefonso', daysAgo: 21, images: ['repair.jpg'],
    description: 'Motorcycle tire patch ₱80, tricycle ₱120. Open 24 hours along the highway. Emergency roadside within San Ildefonso, add ₱200.',
    attributes: { specialty: 'Motorcycle', home_service: true } },
  { owner: 'toto.welding', category: 'construction', type: 'SERVICE', title: 'Steel gate and window grills, made to order', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 8, images: ['welding2.jpg'],
    description: 'Custom gates, grills and railings. Send the measurements and a photo of the design you like for a quote. Installation included within Bulacan.',
    attributes: { trade: 'Welder', crew_size: 3 } },
  { owner: 'kap.tolits', category: 'construction', type: 'SERVICE', title: 'Tile setting and bathroom renovation', price: null, unit: 'QUOTE',
    municipality: 'San Ildefonso', daysAgo: 16, images: ['construction.jpg'],
    description: 'Complete bathroom renovation or tile setting only. We handle the plumbing and waterproofing too. Free site visit and estimate within San Ildefonso.',
    attributes: { trade: 'Mason', crew_size: 4 } },

  // ---- More goods ----
  { owner: 'jm.tech', category: 'phone-tablet', type: 'SELL', title: 'Cherry Mobile, basic phone for lolo and lola', price: 1200, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 8, images: ['phone.jpg'],
    description: 'Big buttons, loud ringtone, dual SIM, long battery. Brand new with warranty. Perfect for seniors who just need calls and text.',
    attributes: { brand: 'Other', model: 'Cherry Mobile', storage_gb: 4, condition: 'Brand new', with_box: true } },
  { owner: 'nene.sari', category: 'appliances', type: 'SELL', title: 'Rice cooker 1.8L, brand new', price: 850, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 13, images: ['fan.jpg'],
    description: 'Brand new, extra stock from the store. 1.8 litres, good for a family of five. With steamer tray.',
    attributes: { appliance_type: 'Rice cooker', brand: 'Hanabishi', condition: 'Brand new' } },
  { owner: 'tessie.b', category: 'appliances', type: 'SELL', title: 'Two-door refrigerator, 7 cu ft', price: 8500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 7, images: ['fridge.jpg'],
    description: 'Working well, freezer is strong. Some rust at the back but does not affect cooling. Buyer arranges pick-up, we can help load it.',
    attributes: { appliance_type: 'Refrigerator', brand: 'Condura', condition: 'Used' } },
  { owner: 'edgar.p', category: 'power-tools', type: 'RENT', title: 'Concrete mixer for rent, per day', price: 900, unit: 'PER_DAY', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 18, images: ['tools.jpg'],
    description: 'One-bagger mixer. ₱900 per day, ₱4,500 per week. You arrange the hauling, or we deliver within San Ildefonso for ₱400 both ways.',
    attributes: { tool_type: 'Other', brand: 'Local', power_w: 2200, condition: 'Used' } },
  { owner: 'grace.l', category: 'furniture', type: 'SELL', title: 'Wooden bed frame, queen size', price: 5500, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 9, images: ['bed.jpg'],
    description: 'Solid wood queen frame with headboard. No mattress. Sturdy, walang kalog. Buyer picks up, can be disassembled.',
    attributes: { furniture_type: 'Bed', material: 'Wood', condition: 'Used' } },
  { owner: 'nene.sari', category: 'furniture', type: 'SELL', title: 'Plastic monobloc chairs, 20 pieces', price: 3000, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 24, images: ['sofa.jpg'],
    description: 'Twenty monobloc chairs, used for our store. ₱150 each or ₱3,000 take all. Some have scratches but all are sturdy.',
    attributes: { furniture_type: 'Chairs', material: 'Plastic', condition: 'Used' } },
  { owner: 'dely.farm', category: 'livestock', type: 'SELL', title: 'Ready-to-lay pullets, 5 months old', price: 320, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 5, images: ['chicken.jpg'],
    description: 'Vaccinated pullets, about to start laying. ₱320 each, discount for ten heads and up. We can hold them for you until you are ready.',
    attributes: { animal: 'Chicken', breed: 'Dekalb', quantity: 40 } },
  { owner: 'ferdie.c', category: 'livestock', type: 'SELL', title: 'Piglets for fattening, 25 to 30 days', price: 3800, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 10, images: ['pig.jpg'],
    description: 'Healthy weaned piglets, already vaccinated and dewormed. ₱3,800 each. Free feeding guide for first-time raisers.',
    attributes: { animal: 'Pig', breed: 'Landrace cross', quantity: 12 } },
  { owner: 'edgar.p', category: 'livestock', type: 'SELL', title: 'Itik ducklings, one week old', price: 85, unit: 'TOTAL',
    municipality: 'San Ildefonso', daysAgo: 15, images: ['duck.jpg'],
    description: 'One-week-old itik, good for balut production later. ₱85 each, minimum ten heads.',
    attributes: { animal: 'Duck', breed: 'Itik', quantity: 50 } },
  { owner: 'dely.farm', category: 'farm-supplies', type: 'SELL', title: 'Organic fertiliser, vermicast per sack', price: 350, unit: 'TOTAL', negotiable: true,
    municipality: 'San Ildefonso', daysAgo: 12, images: ['vegetables.jpg'],
    description: 'Pure vermicast from our worm beds. 25kg per sack. Good for vegetables and ornamentals. Delivery for five sacks and up.',
    attributes: { supply_type: 'Fertiliser' } },
]

/**
 * The trust graph: how much each viewer's TrustClub network vouches for each
 * poster. Directed, so it is written from the viewer's side.
 *
 * juan.santos is the demo account with the widest view — log in as him to see
 * ranking work across the whole board.
 */
export const DEMO_TRUST: Record<string, Record<string, number>> = {
  'juan.santos': {
    'ruben.dlc': 1240, 'marites.g': 860, 'boyet.motors': 640, 'lorna.catering': 520,
    'rico.hauling': 410, 'lito.reyes': 320, 'dado.trike': 260, 'noel.aircon': 210,
    'jm.tech': 180, 'toto.welding': 155, 'dely.farm': 120, 'weng.h': 95,
    'edgar.p': 70, 'nene.sari': 55, 'kap.tolits': 40, 'ana.cruz': 0,
    'benjie.r': 0, 'grace.l': 0, 'tessie.b': 0, 'mylene.s': 0,
    'aling.baby': 940, 'joy.nails': 780, 'sunshine.laundry': 690, 'rr.printing': 575,
    'kuya.jhon': 480, 'mang.tino': 430, 'nanay.rose': 365, 'aqua.pure': 290,
    'teacher.mia': 245, 'barber.dan': 190, 'thrift.ph': 135, 'hilot.remy': 110,
    'aling.puring': 85, 'jomar.gas': 50, 'tita.beth': 0,
  },
  'ana.cruz': {
    'jm.tech': 980, 'noel.aircon': 720, 'tessie.b': 540, 'mylene.s': 330,
    'juan.santos': 240, 'ruben.dlc': 180, 'marites.g': 90, 'weng.h': 45,
    'lorna.catering': 0, 'dely.farm': 0, 'toto.welding': 0,
    'joy.nails': 1150, 'thrift.ph': 820, 'sunshine.laundry': 460, 'tita.beth': 310,
    'barber.dan': 175, 'aqua.pure': 120, 'aling.baby': 65, 'kuya.jhon': 0,
  },
  'weng.h': {
    'marites.g': 1100, 'boyet.motors': 890, 'jhun.tutor': 610, 'juan.santos': 300,
    'lorna.catering': 205, 'ruben.dlc': 150, 'edgar.p': 60, 'ana.cruz': 0,
    'teacher.mia': 1320, 'sunshine.laundry': 970, 'mang.tino': 540, 'nanay.rose': 420,
    'hilot.remy': 265, 'aqua.pure': 130, 'joy.nails': 75, 'jomar.gas': 0,
  },
  'kl-staff': {
    'ruben.dlc': 400, 'juan.santos': 380, 'marites.g': 350, 'jm.tech': 300,
    'lorna.catering': 260, 'dely.farm': 200, 'aling.baby': 330, 'rr.printing': 280,
    'kuya.jhon': 240, 'joy.nails': 220, 'sunshine.laundry': 180,
  },
}
